### ISSUE TITLE
Using -- on a class will throw an error

### ISSUE THREAD

**Issue by wmerussi** [kristerkari/react-native-stylus-transformer#4]
When trying to use classes with modifiers, like BEM, it throws the error:
`SyntaxError: .../.../page.js: Unexpected token, expected } (12:35) at page.js:12:35`

Example:

`font.styl`
```stylus
.font
  color: red

  &__title
    color: green

  &--blue
    color: blue
```

`page.js`
```javascript
// This works
<Text style={ styles.font }>Text</Text>

// This works
<Text style={ styles.font__title }>Text</Text>

// This won't work
<Text style={ styles.font--blue }>Text</Text>
```

**Comment by wmerussi** [comment]
I guess I fond the solution, it's required to call the class as an array:
`<Text style={ styles['font--blue'] }>Text</Text>`

**Comment by wmerussi** [comment]
If you'd like, I've opened a fork to add this information on `README`
https://github.com/wmerussi/react-native-stylus-transformer

**Comment by kristerkari** [comment]
@wmerussi Thanks!

`styles.font--blue` is something that Javascript does not support, and that's why you need the bracket syntax. 

We can to add you example to the README, please make a PR and I will merge it 👍

**Comment by wmerussi** [comment]
Sweet, thanks for it, I'm quite new to JS and still learning.
Here is the PR: https://github.com/kristerkari/react-native-stylus-transformer/pull/5

If you'd like any changes, please, let me know :slightly_smiling_face:

**Comment by kristerkari** [comment]
It's ok, I want my projects to be easy to use even for beginners of Javascript, so it makes sense to make the documentation as clear as possible 👍

**Comment by kristerkari** [comment]
I'm closing this issue now as it is documented.

I'll add the same example to my other transformer repos (Sass, Less, PostCSS, CSS).
